version: "3.7"

services:
  "7.3-0.41.1-bgs-on":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-laravel:7.3.build"
    depends_on:
      - agent
    ports:
      - 7777:80
    environment:
      - DD_SERVICE_NAME=7.3-0.41.1-bgs-on
      - DD_AGENT_HOST=agent
      - DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
      # - DD_TRACE_DEBUG=true
      - TRACER_DOWNLOAD_URL=https://github.com/DataDog/dd-trace-php/releases/download/0.41.1/datadog-php-tracer_0.41.1_amd64.deb
    command: [ "./local-run.sh" ]

  "7.3-0.41.1-bgs-off":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-laravel:7.3.build"
    depends_on:
      - agent
    ports:
      - 7778:80
    environment:
      - DD_SERVICE_NAME=7.3-0.41.1-bgs-off
      - DD_AGENT_HOST=agent
      - DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=false
      # - DD_TRACE_DEBUG=true
      - TRACER_DOWNLOAD_URL=https://github.com/DataDog/dd-trace-php/releases/download/0.41.1/datadog-php-tracer_0.41.1_amd64.deb
    command: [ "./local-run.sh" ]

  "7.3-none":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-laravel:7.3.build"
    depends_on:
      - agent
    ports:
      - 7779:80
    environment:
      - DD_SERVICE_NAME=7.3-none
      - DD_AGENT_HOST=agent
    command: [ "./local-run.sh" ]

  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_ENV=testenv
